import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavOutline from "./NavOutline";
import { FaFacebook, FaTwitter, FaInstagram, FaLinkedin } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          `${geistSans.variable} ${geistMono.variable} antialiased` +
          "bg-amber-600"
        }
      >
        <NavOutline />
        {children}
        <footer className="border-t-2 border-blue-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 flex flex-col md:flex-row justify-between items-center">
        <p className=" text-sm">
          © M'R Robin Ahmed..?
        </p>
        <p className=" text-sm">
          © 2025 M'R Robin. All rights reserved.
        </p>

        <div className="flex space-x-6 mt-4 md:mt-0">
          <a
            aria-label="Facebook"
            className="  transition"
            href="#"
          >
            <FaFacebook className="text-lg" />
          </a>
          <a
            aria-label="Twitter"
            className="  transition"
            href="#"
          >
            <FaTwitter className="text-lg" />
          </a>
          <a
            aria-label="Instagram"
            className="  transition"
            href="#"
          >
            <FaInstagram className="text-lg" />
          </a>
          <a
            aria-label="LinkedIn"
            className="  transition"
            href="#"
          >
            <FaLinkedin className="text-lg" />
          </a>
        </div>
      </div>
    </footer>
      </body>
    </html>
  );
}
